---
title: "Adam Rawles's resume"
author: Adam Rawles
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: TRUE
---

Aside
================================================================================


[Adam Rawles](https://arawles.co.uk){width=80%}


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> adamrawles@hotmail.co.uk
- <i class="fa fa-github"></i> [github.com/ARawles](https://github.com/ARawles)
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Many years of experience both using and teaching the R programming language.   

- Experienced in applying various statistical methods with R, including machine learning, generalised linear modelling and Bayesian modelling.   

- Familiarity with JavaScript and
Python.   

- Extensive experience in data extraction from SQL databases and experience with database design   

- R package developement experience.   



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<a href = "https://arawles.co.uk/cv/cv.pdf">PDF Version</a>

Last updated on `r Sys.Date()`.


Main
================================================================================

Adam Rawles {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Cardiff University

First Class Honors - BSc. Psychology

Cardiff, UK

2014 - 2018 

Project: An Evaluation of Spatial Representations of Order and the Efficacy of Online Studies

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### SPRINt Research Assistant

School of Psychology, Cardiff

Cardiff, UK

June 2017 - July 2017

- Evaluated multiple publication bias correction methods via R-based simulations.
- Collaborated with other researchers through GitHub and Slack.


### Research Assistant

School of Psychology, Cardiff

Cardiff, UK

2016

- Worked with Professor Mark Johansen to explore the relationship between paranormal beliefs and confirmation bias.
- Designed and implemented a testing methodology.

### Final Year Project

School of Psychology, Cardiff

Cardiff, UK

2018

- Designed an online and lab-based version of a cognitive psychology experiment testing the relationship between actual and represented differences between items in a list.
- Extended the functionality of the developing PsychoJS software to run the experiment online.
- Analysed the difference in responses between the online and lab versions of the study as a secondary research topic.


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Analyst

Guernsey Financial Services Commission

Guernsey, CI

2019 - Current

- Recreated and automated the generation of various data reports using RMarkdown and pagedown to produce interactive HTML and PDF versions.
- Created a Shiny-based UI for users to interact with the report generator.
- Spearheaded an effort to better utilise the available data for inferential statistical analysis, including clustering and regression analyses.
- Further developed and delivered R training materials ([teacheR](https://teacher.arawles.co.uk) and [opeRate](https://operate.arawles.co.uk))

### Graduate Data Analyst

ELEXON

London, UK

2018 - 2019

- Performance Assurance Review team   
    + 6 months
    + Implemented a new risk simulation, utilising a Monte-Carlo methodology in R to better estimate the financial cost associated with specific risks.
- Market Analysis team
    + Automated and updated market reports, allowing them to be automatically published to the ELEXON website with custom HTML widgets to allow for greater user interaction.
    + Developed an R package to facilitate the extraction of energy-related data from the Balancing Mechanism Reporting Service API provided by ELEXON called BMRSr.

- First developed materials to teach R to beginners that would eventually become the [teacheR](https://teacher.arawles.co.uk) and [opeRate](https://operate.arawles.co.uk) books.



Projects {data-icon=project-diagram}
--------------------------------------------------------------------------------

### teacheR

A book aimed at beginners to the R programming language. Hosted at https://teacher.arawles.co.uk.

N/A

N/A

### opeRate

An advanced book focusing on applying R skills to data analysis projects. Hosted at https://operate.arawles.co.uk.

N/A

N/A

### BMRSr

An R package that provides functions to better access the Balancing Mechanism Reporting Service API provided by ELEXON. This API allows access to a large repository of historical and realtime energy-related data. Documentation hosted at https:///bmrsr.arawles.co.uk.

N/A

N/A

### faviconR

An R package providing a set of lightweight wrapper functions to the [RealFaviconGenerator.net](https://realfavicongenerator.net) API, used to generate favicons.

N/A

N/A


